name: dictionary_api
description: A Flutter Project for calling dictionary_api
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.2

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
