name: dictionary_api
description: A Flutter Project for calling dictionary_api
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  provider: ^6.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  meta: ^1.9.1

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
