name: dictionary_api
description: A Flutter Project for calling dictionary_api
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
